import type { Theme } from './types';

export const defaultTheme: Theme = {
  id: 'default',
  name: '默认蓝',
  description: '简洁清新，蓝色点缀，适合通用资讯类文章',
  base: {
    color: '#3f3f3f',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    'font-size': '15px',
    'line-height': '1.75',
    'letter-spacing': '0.05em',
  },
  styles: {
    container: {
      'max-width': '100%',
      margin: '0 auto',
      padding: '0',
      color: '#3f3f3f',
      'font-size': '15px',
      'line-height': '1.75',
      'letter-spacing': '0.05em',
      'word-break': 'break-word',
    },
    h1: {
      display: 'table',
      padding: '0 1em',
      'border-bottom': '2px solid #1e6bb8',
      margin: '2em auto 1em',
      color: '#1e6bb8',
      'font-size': '1.4em',
      'font-weight': 'bold',
      'text-align': 'center',
    },
    h2: {
      display: 'table',
      padding: '0 0.6em',
      margin: '2em auto 1em',
      'border-radius': '4px',
      color: '#fff',
      background: '#1e6bb8',
      'font-size': '1.2em',
      'font-weight': 'bold',
      'text-align': 'center',
    },
    h3: {
      'padding-left': '8px',
      'border-left': '4px solid #1e6bb8',
      margin: '1.6em 8px 0.8em 0',
      color: '#1e6bb8',
      'font-size': '1.1em',
      'font-weight': 'bold',
      'line-height': '1.2',
    },
    h4: {
      margin: '1.4em 8px 0.6em',
      color: '#1e6bb8',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h5: {
      margin: '1.2em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h6: {
      margin: '1em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
      color: '#666',
    },
    p: {
      margin: '1.2em 8px',
      'letter-spacing': '0.05em',
      color: '#3f3f3f',
      'text-align': 'justify',
    },
    strong: {
      color: '#1e6bb8',
      'font-weight': 'bold',
    },
    em: {
      'font-style': 'italic',
      color: '#3f3f3f',
    },
    del: {
      color: '#999',
    },
    a: {
      color: '#1e6bb8',
      'border-bottom': '1px solid #1e6bb8',
      'text-decoration': 'none',
    },
    ul: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      color: '#3f3f3f',
      'list-style': 'disc',
    },
    ol: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      color: '#3f3f3f',
      'list-style': 'decimal',
    },
    li: {
      margin: '0.4em 0',
      'line-height': '1.75',
    },
    blockquote: {
      margin: '1.2em 8px',
      padding: '0.8em 1em',
      'border-left': '4px solid #1e6bb8',
      background: '#f7f9fc',
      color: '#555',
      'border-radius': '4px',
    },
    blockquoteP: {
      margin: '0',
      'letter-spacing': '0.05em',
      color: '#555',
    },
    hr: {
      border: 'none',
      'border-top': '1px solid #e4e4e4',
      margin: '2em 0',
    },
    code: {
      padding: '2px 6px',
      'border-radius': '4px',
      background: 'rgba(30,107,184,0.08)',
      color: '#1e6bb8',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '0.9em',
    },
    pre: {
      margin: '1.4em 8px',
      padding: '1em',
      'border-radius': '6px',
      background: '#1e1e2f',
      color: '#e6e6e6',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      'overflow-x': 'auto',
    },
    preCode: {
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      'border-radius': '0',
      'font-size': '13px',
      'white-space': 'pre',
    },
    img: {
      display: 'block',
      margin: '1.2em auto',
      'max-width': '100%',
      'border-radius': '4px',
    },
    table: {
      'border-collapse': 'collapse',
      margin: '1.2em 8px',
      'font-size': '14px',
      width: 'auto',
    },
    thead: {
      background: '#1e6bb8',
      color: '#fff',
    },
    th: {
      padding: '0.4em 0.8em',
      border: '1px solid #d6e4f0',
      'font-weight': 'bold',
      'text-align': 'left',
    },
    tr: {},
    td: {
      padding: '0.4em 0.8em',
      border: '1px solid #d6e4f0',
    },
    figure: {
      margin: '1.4em 0',
      'text-align': 'center',
    },
    figcaption: {
      'font-size': '12px',
      color: '#999',
      'text-align': 'center',
      'margin-top': '0.4em',
    },
  },
};
