import type { Theme } from './types';

export const elegantTheme: Theme = {
  id: 'elegant',
  name: '优雅绿',
  description: '配色清雅，绿色基调，适合生活、文学、随笔类内容',
  base: {
    color: '#3f3f3f',
    'font-family':
      '"Source Han Serif SC", "Songti SC", "Noto Serif SC", "Times New Roman", serif',
    'font-size': '15px',
    'line-height': '1.85',
    'letter-spacing': '0.06em',
  },
  styles: {
    container: {
      'max-width': '100%',
      margin: '0 auto',
      padding: '0',
      color: '#3f3f3f',
      'font-family':
        '"Source Han Serif SC", "Songti SC", "Noto Serif SC", "Times New Roman", serif',
      'font-size': '15px',
      'line-height': '1.85',
      'letter-spacing': '0.06em',
      'word-break': 'break-word',
    },
    h1: {
      margin: '2em auto 1.2em',
      color: '#2d6a4f',
      'font-size': '1.5em',
      'font-weight': 'bold',
      'text-align': 'center',
      'letter-spacing': '0.2em',
    },
    h2: {
      display: 'inline-block',
      padding: '0 0.6em',
      margin: '2em 0 1em',
      'border-bottom': '2px solid #2d6a4f',
      color: '#2d6a4f',
      'font-size': '1.25em',
      'font-weight': 'bold',
    },
    h3: {
      'padding-left': '0.6em',
      'border-left': '3px solid #2d6a4f',
      margin: '1.6em 8px 0.8em 0',
      color: '#2d6a4f',
      'font-size': '1.1em',
      'font-weight': 'bold',
    },
    h4: {
      margin: '1.4em 8px 0.6em',
      color: '#2d6a4f',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h5: {
      margin: '1.2em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h6: {
      margin: '1em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
      color: '#666',
    },
    p: {
      margin: '1.2em 8px',
      'text-indent': '2em',
      'letter-spacing': '0.06em',
      color: '#3f3f3f',
      'text-align': 'justify',
    },
    strong: {
      color: '#2d6a4f',
      'font-weight': 'bold',
    },
    em: {
      'font-style': 'italic',
    },
    del: {
      color: '#999',
    },
    a: {
      color: '#2d6a4f',
      'border-bottom': '1px solid #2d6a4f',
      'text-decoration': 'none',
    },
    ul: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'disc',
    },
    ol: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'decimal',
    },
    li: {
      margin: '0.4em 0',
      'line-height': '1.85',
    },
    blockquote: {
      margin: '1.4em 8px',
      padding: '0.8em 1.2em',
      'border-left': '4px solid #95d5b2',
      background: '#f1faf4',
      color: '#5a5a5a',
      'border-radius': '4px',
      'font-style': 'italic',
    },
    blockquoteP: {
      margin: '0',
      'text-indent': '0',
      color: '#5a5a5a',
    },
    hr: {
      border: 'none',
      'border-top': '1px dashed #95d5b2',
      margin: '2em 0',
    },
    code: {
      padding: '2px 6px',
      'border-radius': '4px',
      background: 'rgba(45,106,79,0.08)',
      color: '#2d6a4f',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '0.9em',
    },
    pre: {
      margin: '1.4em 8px',
      padding: '1em',
      'border-radius': '6px',
      background: '#1b3a2d',
      color: '#e6efe9',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      'overflow-x': 'auto',
    },
    preCode: {
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      'border-radius': '0',
      'font-size': '13px',
      'white-space': 'pre',
    },
    img: {
      display: 'block',
      margin: '1.2em auto',
      'max-width': '100%',
      'border-radius': '4px',
    },
    table: {
      'border-collapse': 'collapse',
      margin: '1.2em 8px',
      'font-size': '14px',
    },
    thead: {
      background: '#2d6a4f',
      color: '#fff',
    },
    th: {
      padding: '0.4em 0.8em',
      border: '1px solid #c8e6d1',
      'font-weight': 'bold',
    },
    tr: {},
    td: {
      padding: '0.4em 0.8em',
      border: '1px solid #c8e6d1',
    },
    figure: {
      margin: '1.4em 0',
      'text-align': 'center',
    },
    figcaption: {
      'font-size': '12px',
      color: '#999',
      'text-align': 'center',
      'margin-top': '0.4em',
    },
  },
};
