import type { Theme } from './types';

export const pinkTheme: Theme = {
  id: 'pink',
  name: '少女粉',
  description: '甜美粉色调，圆润可爱，适合美食、生活、情感类公众号',
  base: {
    color: '#4a3640',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    'font-size': '15px',
    'line-height': '1.8',
    'letter-spacing': '0.05em',
  },
  styles: {
    container: {
      'max-width': '100%',
      margin: '0 auto',
      padding: '0',
      color: '#4a3640',
      'font-size': '15px',
      'line-height': '1.8',
      'letter-spacing': '0.05em',
      'word-break': 'break-word',
    },
    h1: {
      margin: '2em auto 1em',
      padding: '0.3em 0.8em',
      'border-radius': '999px',
      background: 'linear-gradient(135deg, #ff8fb1, #ffc1d6)',
      color: '#fff',
      'font-size': '1.3em',
      'font-weight': 'bold',
      'text-align': 'center',
      display: 'table',
    },
    h2: {
      margin: '2em 8px 1em',
      'border-bottom': '2px dashed #ff8fb1',
      color: '#d6336c',
      'font-size': '1.2em',
      'font-weight': 'bold',
      'padding-bottom': '0.2em',
    },
    h3: {
      'padding-left': '0.6em',
      'border-left': '4px solid #ff8fb1',
      margin: '1.6em 8px 0.8em 0',
      color: '#d6336c',
      'font-size': '1.1em',
      'font-weight': 'bold',
    },
    h4: {
      margin: '1.4em 8px 0.6em',
      color: '#d6336c',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h5: {
      margin: '1.2em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h6: {
      margin: '1em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
      color: '#999',
    },
    p: {
      margin: '1.2em 8px',
      'letter-spacing': '0.05em',
      color: '#4a3640',
      'text-align': 'justify',
    },
    strong: {
      color: '#d6336c',
      'font-weight': 'bold',
    },
    em: {
      'font-style': 'italic',
    },
    del: {
      color: '#999',
    },
    a: {
      color: '#d6336c',
      'border-bottom': '1px solid #d6336c',
      'text-decoration': 'none',
    },
    ul: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'disc',
    },
    ol: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'decimal',
    },
    li: {
      margin: '0.4em 0',
      'line-height': '1.8',
    },
    blockquote: {
      margin: '1.2em 8px',
      padding: '0.8em 1em',
      'border-left': '4px solid #ff8fb1',
      background: '#fff5f8',
      color: '#7a5260',
      'border-radius': '8px',
    },
    blockquoteP: {
      margin: '0',
      color: '#7a5260',
    },
    hr: {
      border: 'none',
      'border-top': '1px dashed #ffc1d6',
      margin: '2em 0',
    },
    code: {
      padding: '2px 6px',
      'border-radius': '4px',
      background: 'rgba(214,51,108,0.08)',
      color: '#d6336c',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '0.9em',
    },
    pre: {
      margin: '1.4em 8px',
      padding: '1em',
      'border-radius': '8px',
      background: '#3a2530',
      color: '#fde2eb',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      'overflow-x': 'auto',
    },
    preCode: {
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      'border-radius': '0',
      'font-size': '13px',
      'white-space': 'pre',
    },
    img: {
      display: 'block',
      margin: '1.2em auto',
      'max-width': '100%',
      'border-radius': '8px',
    },
    table: {
      'border-collapse': 'collapse',
      margin: '1.2em 8px',
      'font-size': '14px',
    },
    thead: {
      background: '#ff8fb1',
      color: '#fff',
    },
    th: {
      padding: '0.4em 0.8em',
      border: '1px solid #ffc1d6',
      'font-weight': 'bold',
    },
    tr: {},
    td: {
      padding: '0.4em 0.8em',
      border: '1px solid #ffc1d6',
    },
    figure: {
      margin: '1.4em 0',
      'text-align': 'center',
    },
    figcaption: {
      'font-size': '12px',
      color: '#bbb',
      'text-align': 'center',
      'margin-top': '0.4em',
    },
  },
};
