import type { Theme } from './types';

export const techTheme: Theme = {
  id: 'tech',
  name: '极客橙',
  description: '科技感配色，强调代码与列表，适合技术、产品类文章',
  base: {
    color: '#2c3e50',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    'font-size': '15px',
    'line-height': '1.75',
    'letter-spacing': '0.04em',
  },
  styles: {
    container: {
      'max-width': '100%',
      margin: '0 auto',
      padding: '0',
      color: '#2c3e50',
      'font-size': '15px',
      'line-height': '1.75',
      'letter-spacing': '0.04em',
      'word-break': 'break-word',
    },
    h1: {
      margin: '2em auto 1em',
      padding: '0.4em 0',
      'border-top': '3px solid #f97316',
      'border-bottom': '1px solid #f97316',
      color: '#1f2937',
      'font-size': '1.4em',
      'font-weight': 'bold',
      'text-align': 'center',
    },
    h2: {
      display: 'inline-block',
      padding: '0.2em 0.8em',
      margin: '2em 0 1em',
      'border-radius': '4px',
      background: 'linear-gradient(135deg, #f97316, #fb923c)',
      color: '#fff',
      'font-size': '1.2em',
      'font-weight': 'bold',
    },
    h3: {
      'padding-left': '0.6em',
      'border-left': '4px solid #f97316',
      margin: '1.6em 8px 0.8em 0',
      color: '#1f2937',
      'font-size': '1.1em',
      'font-weight': 'bold',
    },
    h4: {
      margin: '1.4em 8px 0.6em',
      color: '#f97316',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h5: {
      margin: '1.2em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
    },
    h6: {
      margin: '1em 8px 0.4em',
      'font-size': '1em',
      'font-weight': 'bold',
      color: '#666',
    },
    p: {
      margin: '1.2em 8px',
      'letter-spacing': '0.04em',
      color: '#2c3e50',
      'text-align': 'justify',
    },
    strong: {
      color: '#f97316',
      'font-weight': 'bold',
    },
    em: {
      'font-style': 'italic',
    },
    del: {
      color: '#999',
    },
    a: {
      color: '#f97316',
      'border-bottom': '1px solid #f97316',
      'text-decoration': 'none',
    },
    ul: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'disc',
    },
    ol: {
      margin: '1em 8px',
      'padding-left': '1.6em',
      'list-style': 'decimal',
    },
    li: {
      margin: '0.4em 0',
      'line-height': '1.75',
    },
    blockquote: {
      margin: '1.2em 8px',
      padding: '0.8em 1em',
      'border-left': '4px solid #f97316',
      background: '#fff7ed',
      color: '#7c2d12',
      'border-radius': '4px',
    },
    blockquoteP: {
      margin: '0',
      color: '#7c2d12',
    },
    hr: {
      border: 'none',
      'border-top': '1px dashed #f97316',
      margin: '2em 0',
    },
    code: {
      padding: '2px 6px',
      'border-radius': '4px',
      background: 'rgba(249,115,22,0.1)',
      color: '#c2410c',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '0.9em',
    },
    pre: {
      margin: '1.4em 8px',
      padding: '1em',
      'border-radius': '6px',
      background: '#0f172a',
      color: '#e2e8f0',
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      'overflow-x': 'auto',
    },
    preCode: {
      'font-family': '"SF Mono", Consolas, Menlo, Monaco, monospace',
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      'border-radius': '0',
      'font-size': '13px',
      'white-space': 'pre',
    },
    img: {
      display: 'block',
      margin: '1.2em auto',
      'max-width': '100%',
      'border-radius': '4px',
      'box-shadow': '0 4px 16px rgba(0,0,0,0.08)',
    },
    table: {
      'border-collapse': 'collapse',
      margin: '1.2em 8px',
      'font-size': '14px',
    },
    thead: {
      background: '#f97316',
      color: '#fff',
    },
    th: {
      padding: '0.4em 0.8em',
      border: '1px solid #fed7aa',
      'font-weight': 'bold',
    },
    tr: {},
    td: {
      padding: '0.4em 0.8em',
      border: '1px solid #fed7aa',
    },
    figure: {
      margin: '1.4em 0',
      'text-align': 'center',
    },
    figcaption: {
      'font-size': '12px',
      color: '#999',
      'text-align': 'center',
      'margin-top': '0.4em',
    },
  },
};
