# -*- coding: utf-8 -*-
"""上海板块 × 学区融合数据（基于公开信息与差异化选房逻辑整理）。"""

# 各字段说明见 README；数值 1–5，越高表示该维度越「强/高/优」
# population_hollow: 人口空心化程度（居住人口相对学校容量偏少）
# new_resident_ratio: 新上海人/外来常住人口占比（越高竞争越卷）
# school_competition: 升学竞争强度
# primary_quality / middle_quality: 公办小学/初中口碑（非官方排名）
# price_low / price_high: 典型老破小/小户型总价区间（万元）

PLATES = [
    # ── 黄浦区（学籍对口，人口持续流出，纪要强烈推荐）──
    {"district": "黄浦", "plate": "半淞园路", "street": "半淞园路街道", "primary_schools": "上实南校小学部、黄浦一中心", "middle_schools": "市八、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 4, "middle_quality": 4, "price_low": 250, "price_high": 450, "notes": "滨江+学区可兼得；老上海人口流出"},
    {"district": "黄浦", "plate": "打浦桥", "street": "打浦桥街道", "primary_schools": "黄浦一中心、卢湾二中心", "middle_schools": "向明初、卢湾中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 4, "middle_quality": 4, "price_low": 300, "price_high": 600, "notes": "老上海人聚集；新天地辐射"},
    {"district": "黄浦", "plate": "五里桥", "street": "五里桥街道", "primary_schools": "卢湾二中心、黄浦一中心", "middle_schools": "向明初、卢湾中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 3, "middle_quality": 4, "price_low": 280, "price_high": 500, "notes": "汇龙新城等标杆盘所在"},
    {"district": "黄浦", "plate": "老西门", "street": "老西门街道", "primary_schools": "蓬莱二小、黄浦一中心", "middle_schools": "市八、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 4, "price_low": 200, "price_high": 380, "notes": "老城厢，人口空心化明显"},
    {"district": "黄浦", "plate": "豫园", "street": "豫园街道", "primary_schools": "福佑路第一小学", "middle_schools": "市八、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 1, "school_competition": 2, "primary_quality": 3, "middle_quality": 4, "price_low": 200, "price_high": 350, "notes": "旅游+老居民混居，生源竞争小"},
    {"district": "黄浦", "plate": "外滩", "street": "外滩街道", "primary_schools": "北京东路小学", "middle_schools": "格致初、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 1, "school_competition": 2, "primary_quality": 3, "middle_quality": 4, "price_low": 220, "price_high": 400, "notes": "老上海核心，常住人口少"},
    {"district": "黄浦", "plate": "南京东路", "street": "南京东路街道", "primary_schools": "北京东路小学", "middle_schools": "格致初、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 1, "school_competition": 2, "primary_quality": 3, "middle_quality": 4, "price_low": 230, "price_high": 420, "notes": "商业为主，居住人口空心化"},
    {"district": "黄浦", "plate": "淮海中路", "street": "淮海中路街道", "primary_schools": "巨鹿路第一小学、卢湾二中心", "middle_schools": "向明初、格致初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 4, "middle_quality": 4, "price_low": 350, "price_high": 800, "notes": "新天地/淮海路，双学区热门"},
    {"district": "黄浦", "plate": "瑞金二路", "street": "瑞金二路街道", "primary_schools": "卢湾二中心、海华实小", "middle_schools": "向明初、卢湾中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 4, "middle_quality": 4, "price_low": 300, "price_high": 650, "notes": "北卢湾，梧桐区"},
    {"district": "黄浦", "plate": "小东门", "street": "小东门街道", "primary_schools": "董家渡路第二小学", "middle_schools": "市八、大同初", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 4, "price_low": 200, "price_high": 380, "notes": "动迁后人口流出，竞争压力小"},

    # ── 杨浦区 ──
    {"district": "杨浦", "plate": "东外滩/杨浦滨江", "street": "定海路/平凉路", "primary_schools": "杨浦小学、杭州路第一小学", "middle_schools": "杨浦初级、东辽阳中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 3, "price_low": 200, "price_high": 400, "notes": "纪要强烈推荐；旧改人口流出，竞争小于内卷新区"},
    {"district": "杨浦", "plate": "鞍山", "street": "控江路街道", "primary_schools": "打一小学", "middle_schools": "鞍山初级（一般）", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 4, "primary_quality": 4, "middle_quality": 2, "price_low": 250, "price_high": 450, "notes": "挂户口热点；小学强初中弱，摇号后热度下降"},
    {"district": "杨浦", "plate": "控江路", "street": "控江路街道", "primary_schools": "二师附小、控江二小", "middle_schools": "控江中学、鞍山初级", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 220, "price_high": 400, "notes": "传统居住区，竞争中等"},
    {"district": "杨浦", "plate": "五角场", "street": "五角场街道", "primary_schools": "五角场小学、政立路小学", "middle_schools": "五角场初级、同济初级", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 280, "price_high": 500, "notes": "大学城辐射，新上海人较多"},
    {"district": "杨浦", "plate": "新江湾城", "street": "新江湾城街道", "primary_schools": "复旦二附校（九年一贯）", "middle_schools": "复旦二附校", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 600, "price_high": 1200, "notes": "一贯制热门但价高、竞争卷；不符合低成本差异化逻辑"},
    {"district": "杨浦", "plate": "中原", "street": "中原路街道", "primary_schools": "中原路小学", "middle_schools": "中原中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 180, "price_high": 320, "notes": "市区动迁安置区，竞争压力较小"},
    {"district": "杨浦", "plate": "黄兴公园", "street": "延吉新村街道", "primary_schools": "延吉中路小学", "middle_schools": "延吉中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 200, "price_high": 350, "notes": "老工人新村，价格友好"},
    {"district": "杨浦", "plate": "江湾", "street": "殷行街道", "primary_schools": "开鲁新村第二小学", "middle_schools": "开鲁中学", "enrollment": "学籍对口", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 180, "price_high": 300, "notes": "动迁导入较多，竞争中等偏低"},

    # ── 浦东（仅潍坊新村为纪要推荐，其余多数排除）──
    {"district": "浦东", "plate": "潍坊新村", "street": "潍坊新村街道", "primary_schools": "明珠小学A/B区、浦明附小潍坊校区", "middle_schools": "进才中学北校、洋泾菊园（需看对口）", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 5, "middle_quality": 3, "price_low": 200, "price_high": 350, "notes": "⭐纪要首推；崂山一村~十村；老上海聚集、租客少、200–300万"},
    {"district": "浦东", "plate": "陆家嘴", "street": "陆家嘴街道", "primary_schools": "福山外国语小学", "middle_schools": "建平西/进才等（需看户籍）", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 4, "primary_quality": 5, "middle_quality": 4, "price_low": 400, "price_high": 900, "notes": "福外学区热门，竞争激烈；纪要排除大部分浦东"},
    {"district": "浦东", "plate": "梅园", "street": "梅园新村街道", "primary_schools": "福山外国语小学", "middle_schools": "建平西等", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 4, "primary_quality": 5, "middle_quality": 4, "price_low": 350, "price_high": 700, "notes": "福外挂户口集中区"},
    {"district": "浦东", "plate": "源深", "street": "源深路街道", "primary_schools": "福山外国语小学", "middle_schools": "建平西、进才北", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 5, "primary_quality": 5, "middle_quality": 4, "price_low": 500, "price_high": 1000, "notes": "顶级学区，新上海人+高竞争"},
    {"district": "浦东", "plate": "联洋", "street": "花木街道", "primary_schools": "进才实验小学联洋校区", "middle_schools": "进才实验中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 800, "price_high": 1500, "notes": "高端学区，竞争极卷"},
    {"district": "浦东", "plate": "花木", "street": "花木街道", "primary_schools": "海桐小学、建平实验", "middle_schools": "建平实验、进才", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 450, "price_high": 800, "notes": "副中心居住为主，学区热门"},
    {"district": "浦东", "plate": "洋泾", "street": "洋泾街道", "primary_schools": "六师附小、洋泾菊园（九年一贯）", "middle_schools": "洋泾菊园实验学校", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 5, "primary_quality": 4, "middle_quality": 4, "price_low": 400, "price_high": 750, "notes": "一贯制热门，竞争大"},
    {"district": "浦东", "plate": "金桥", "street": "金桥镇", "primary_schools": "建平实验金桥校区", "middle_schools": "建平实验、建平中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 350, "price_high": 650, "notes": "产业+居住混合，新上海人较多"},
    {"district": "浦东", "plate": "张江", "street": "张江镇", "primary_schools": "张江集团/张江高科实验", "middle_schools": "张江集团中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 4, "middle_quality": 4, "price_low": 400, "price_high": 800, "notes": "码农聚集，生育高峰+升学极卷"},
    {"district": "浦东", "plate": "唐镇", "street": "唐镇", "primary_schools": "福山唐城外国语", "middle_schools": "建平实验唐镇", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 4, "middle_quality": 3, "price_low": 350, "price_high": 600, "notes": "导入人口多，竞争卷"},
    {"district": "浦东", "plate": "北蔡", "street": "北蔡镇", "primary_schools": "北蔡中学小学部等", "middle_schools": "北蔡中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 2, "middle_quality": 2, "price_low": 300, "price_high": 550, "notes": "大型居住导入区"},
    {"district": "浦东", "plate": "三林", "street": "三林镇", "primary_schools": "三林中心小等", "middle_schools": "三林中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 500, "notes": "大型导入社区，资源普通价不低"},
    {"district": "浦东", "plate": "前滩", "street": "三林镇", "primary_schools": "惠立/民办为主，公办少", "middle_schools": "华二前滩等", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 1, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 4, "middle_quality": 4, "price_low": 800, "price_high": 2000, "notes": "新兴高端区，竞争极卷"},
    {"district": "浦东", "plate": "周浦", "street": "周浦镇", "primary_schools": "周浦小学等", "middle_schools": "周浦中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 450, "notes": "城乡结合部，导入人口多"},
    {"district": "浦东", "plate": "川沙", "street": "川沙新镇", "primary_schools": "川沙中学南校小学部等", "middle_schools": "川沙中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 250, "price_high": 450, "notes": "副中心规划，竞争中等"},
    {"district": "浦东", "plate": "临港", "street": "南汇新城等", "primary_schools": "临港各公办小", "middle_schools": "临港各公办初", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 150, "price_high": 350, "notes": "远郊新城，学校容量>人口"},
    {"district": "浦东", "plate": "曹路", "street": "曹路镇", "primary_schools": "龚路小学等", "middle_schools": "顾路中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 200, "price_high": 380, "notes": "大型动迁+导入区"},

    # ── 徐汇（九年一贯制需提前3年，用户明年入学不适用）──
    {"district": "徐汇", "plate": "天平路", "street": "天平路街道", "primary_schools": "高安第一小学、向阳小学", "middle_schools": "南洋模范初、位育初", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 500, "price_high": 1200, "notes": "顶级双学区，竞争极卷、价高"},
    {"district": "徐汇", "plate": "湖南路", "street": "湖南路街道", "primary_schools": "建襄小学、向阳小学", "middle_schools": "位育初、南洋模范初", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 550, "price_high": 1300, "notes": "梧桐区顶级学区"},
    {"district": "徐汇", "plate": "徐家汇", "street": "徐家汇街道", "primary_schools": "汇师小学、交大附小", "middle_schools": "南洋模范初、位育初", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 500, "price_high": 1000, "notes": "城市副中心，学区+商业双热门"},
    {"district": "徐汇", "plate": "龙华", "street": "龙华街道", "primary_schools": "龙华小学、汇师小学部分", "middle_schools": "位育初、园南中学", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 400, "price_high": 800, "notes": "滨江开发中，导入增加"},
    {"district": "徐汇", "plate": "徐汇滨江", "street": "斜土/龙华部分", "primary_schools": "日晖新村小学等", "middle_schools": "位育初等", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 3, "middle_quality": 4, "price_low": 600, "price_high": 1500, "notes": "豪宅区，价涨但学区非顶级"},
    {"district": "徐汇", "plate": "田林", "street": "田林街道", "primary_schools": "田林三小、田林四小", "middle_schools": "田林三中、园南中学", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 280, "price_high": 500, "notes": "成熟居住区，竞争中等"},
    {"district": "徐汇", "plate": "漕河泾", "street": "虹梅路街道", "primary_schools": "漕河泾中心小", "middle_schools": "园南中学等", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 350, "price_high": 650, "notes": "IT从业者聚集"},
    {"district": "徐汇", "plate": "康健", "street": "康健新村街道", "primary_schools": "康健外国语实验小学", "middle_schools": "康健外国语实验中学", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 300, "price_high": 550, "notes": "中外环成熟社区"},
    {"district": "徐汇", "plate": "长桥", "street": "长桥街道", "primary_schools": "长桥第二小学", "middle_schools": "长桥中学", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 420, "notes": "价格相对友好，竞争偏低"},
    {"district": "徐汇", "plate": "华泾", "street": "华泾镇", "primary_schools": "华泾小学", "middle_schools": "华泾中学", "enrollment": "学籍对口+派位", "five_year": "全区", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "徐汇南大门，导入增加"},

    # ── 静安 ──
    {"district": "静安", "plate": "南京西路", "street": "南京西路街道", "primary_schools": "静安区第一中心小学", "middle_schools": "市北初、静教院附校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 400, "price_high": 800, "notes": "市中心老破小，人口流出"},
    {"district": "静安", "plate": "静安寺", "street": "静安寺街道", "primary_schools": "静安区第一中心小学", "middle_schools": "市北初、静教院附校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 380, "price_high": 750, "notes": "传统核心区"},
    {"district": "静安", "plate": "江宁路", "street": "江宁路街道", "primary_schools": "静教院附校（九年一贯）", "middle_schools": "静教院附校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 5, "primary_quality": 5, "middle_quality": 5, "price_low": 600, "price_high": 1100, "notes": "顶级一贯制，竞争极卷"},
    {"district": "静安", "plate": "大宁", "street": "大宁路街道", "primary_schools": "大宁国际小学、闸北实验", "middle_schools": "市北初、风华中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 450, "price_high": 850, "notes": "新上海人导入多"},
    {"district": "静安", "plate": "彭浦", "street": "彭浦新村街道", "primary_schools": "彭浦新村第一小学", "middle_schools": "彭浦中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 220, "price_high": 380, "notes": "老闸北，价格友好竞争低"},
    {"district": "静安", "plate": "不夜城", "street": "天目西路街道", "primary_schools": "蕃瓜弄小学等", "middle_schools": "市北初等", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 2, "middle_quality": 3, "price_low": 280, "price_high": 480, "notes": "火车站板块，混合人群"},
    {"district": "静安", "plate": "苏河湾", "street": "北站街道", "primary_schools": "闸北第三中心小", "middle_schools": "市北初", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 4, "price_low": 350, "price_high": 650, "notes": "新开发+旧改混合"},

    # ── 虹口 ──
    {"district": "虹口", "plate": "北外滩", "street": "北外滩街道", "primary_schools": "霍山路小学", "middle_schools": "继光中学、北郊学校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 3, "price_low": 250, "price_high": 450, "notes": "旧改人口流出，竞争较小"},
    {"district": "虹口", "plate": "瑞虹新城", "street": "嘉兴路街道", "primary_schools": "宏星小学", "middle_schools": "新华初、北郊学校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 500, "price_high": 900, "notes": "高端导入社区"},
    {"district": "虹口", "plate": "鲁迅公园", "street": "欧阳路街道", "primary_schools": "红旗小学", "middle_schools": "新华初", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 3, "middle_quality": 4, "price_low": 280, "price_high": 500, "notes": "老上海居住区，人口老龄化"},
    {"district": "虹口", "plate": "曲阳", "street": "曲阳路街道", "primary_schools": "曲阳第二小学", "middle_schools": "曲阳中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 220, "price_high": 380, "notes": "虹口自留地，老居民为主"},
    {"district": "虹口", "plate": "凉城", "street": "凉城新村街道", "primary_schools": "广灵二路小学", "middle_schools": "凉城第二中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 200, "price_high": 350, "notes": "工人新村，竞争低"},
    {"district": "虹口", "plate": "四川北路", "street": "四川北路街道", "primary_schools": "四川北路第一小学", "middle_schools": "新华初", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 3, "primary_quality": 3, "middle_quality": 4, "price_low": 250, "price_high": 450, "notes": "老城区，人口流出"},

    # ── 普陀 ──
    {"district": "普陀", "plate": "长寿路", "street": "长寿路街道", "primary_schools": "曹杨实验小学", "middle_schools": "曹杨二中附属学校", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 300, "price_high": 550, "notes": "传统商业居住混合"},
    {"district": "普陀", "plate": "武宁", "street": "长寿路街道部分", "primary_schools": "武宁路小学", "middle_schools": "梅陇中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 320, "price_high": 580, "notes": "高楼集中区"},
    {"district": "普陀", "plate": "曹杨", "street": "曹杨新村街道", "primary_schools": "曹杨二小、曹杨实验小学", "middle_schools": "曹杨二中附属", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 3, "price_low": 250, "price_high": 420, "notes": "工人新村，老龄化人口空心化"},
    {"district": "普陀", "plate": "真如", "street": "真如镇街道", "primary_schools": "真如文英中心小学", "middle_schools": "真如中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 450, "notes": "副中心规划，竞争中等偏低"},
    {"district": "普陀", "plate": "长风", "street": "长风新村街道", "primary_schools": "华东师范大学附属外国语实验学校", "middle_schools": "华师大四附中", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 4, "middle_quality": 4, "price_low": 450, "price_high": 850, "notes": "近铁+长风生态，导入增加"},
    {"district": "普陀", "plate": "桃浦", "street": "桃浦镇", "primary_schools": "桃浦中心小", "middle_schools": "桃浦中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 220, "price_high": 400, "notes": "化工区转型，竞争较低"},
    {"district": "普陀", "plate": "万里", "street": "万里街道", "primary_schools": "万里城实验小", "middle_schools": "万里城实验", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 400, "price_high": 700, "notes": "中高端导入社区"},

    # ── 长宁 ──
    {"district": "长宁", "plate": "中山公园", "street": "华阳路/江苏路", "primary_schools": "愚一小学、长宁实验小学", "middle_schools": "延安初、天山中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 350, "price_high": 650, "notes": "成熟商业居住"},
    {"district": "长宁", "plate": "天山", "street": "天山路街道", "primary_schools": "天山第一小学", "middle_schools": "天山中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 2, "primary_quality": 3, "middle_quality": 3, "price_low": 300, "price_high": 550, "notes": "老上海居住区，竞争中等偏低"},
    {"district": "长宁", "plate": "古北", "street": "虹桥街道", "primary_schools": "建青实验学校", "middle_schools": "建青实验", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 500, "price_high": 1000, "notes": "国际社区，非传统学区逻辑"},
    {"district": "长宁", "plate": "虹桥", "street": "虹桥街道", "primary_schools": "虹桥机场新村小", "middle_schools": "虹桥中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "成熟社区，竞争偏低"},
    {"district": "长宁", "plate": "北新泾", "street": "新泾镇部分", "primary_schools": "北新泾第二小学", "middle_schools": "北新泾中学", "enrollment": "学籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 3, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "中外环，竞争较低"},

    # ── 闵行（纪要建议排除大部分）──
    {"district": "闵行", "plate": "七宝", "street": "七宝镇", "primary_schools": "七宝明强小学", "middle_schools": "七宝中学/文来等", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 4, "middle_quality": 5, "price_low": 400, "price_high": 750, "notes": "❌纪要排除；新上海人+升学极卷"},
    {"district": "闵行", "plate": "莘庄", "street": "莘庄镇", "primary_schools": "莘松小学", "middle_schools": "莘松中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 350, "price_high": 600, "notes": "❌纪要排除；人口导入大区"},
    {"district": "闵行", "plate": "古美", "street": "古美街道", "primary_schools": "平南小学", "middle_schools": "古美中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 380, "price_high": 650, "notes": "❌纪要排除"},
    {"district": "闵行", "plate": "春申", "street": "梅陇镇", "primary_schools": "闵实验春城/景城", "middle_schools": "莘松中学等", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 4, "middle_quality": 3, "price_low": 400, "price_high": 700, "notes": "❌纪要排除；学区热门"},
    {"district": "闵行", "plate": "梅陇", "street": "梅陇镇", "primary_schools": "梅陇小学", "middle_schools": "梅陇中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 3, "middle_quality": 3, "price_low": 350, "price_high": 600, "notes": "❌纪要排除"},
    {"district": "闵行", "plate": "浦江", "street": "浦江镇", "primary_schools": "浦江第一小学", "middle_schools": "浦江二中", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 450, "notes": "❌纪要排除；大型导入区"},
    {"district": "闵行", "plate": "华漕", "street": "华漕镇", "primary_schools": "华漕中心小", "middle_schools": "华漕中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 300, "price_high": 550, "notes": "❌纪要排除；前湾规划导入"},
    {"district": "闵行", "plate": "颛桥", "street": "颛桥镇", "primary_schools": "颛桥中心小", "middle_schools": "颛桥中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 420, "notes": "❌纪要排除"},

    # ── 宝山（纪要提及竞争大）──
    {"district": "宝山", "plate": "大华", "street": "大场镇", "primary_schools": "大华小学", "middle_schools": "大华中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "大型导入社区"},
    {"district": "宝山", "plate": "顾村", "street": "顾村镇", "primary_schools": "顾村中心小", "middle_schools": "顾村中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 420, "notes": "动迁大居，新上海人集中"},
    {"district": "宝山", "plate": "淞南", "street": "淞南镇", "primary_schools": "淞南中心小", "middle_schools": "淞南中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 220, "price_high": 380, "notes": "竞争中等偏低"},
    {"district": "宝山", "plate": "共康", "street": "庙行镇", "primary_schools": "共康实验小", "middle_schools": "共康中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 4, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 300, "price_high": 520, "notes": "大宁外溢导入"},

    # ── 嘉定（纪要明确排除）──
    {"district": "嘉定", "plate": "嘉定新城", "street": "马陆/菊园", "primary_schools": "嘉定新城各公办小", "middle_schools": "嘉定新城各公办初", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 450, "notes": "❌纪要排除"},
    {"district": "嘉定", "plate": "江桥", "street": "江桥镇", "primary_schools": "江桥中心小", "middle_schools": "江桥中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "❌纪要排除；大虹桥外溢"},
    {"district": "嘉定", "plate": "南翔", "street": "南翔镇", "primary_schools": "南翔小学", "middle_schools": "南翔中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 300, "price_high": 520, "notes": "❌纪要排除"},
    {"district": "嘉定", "plate": "安亭", "street": "安亭镇", "primary_schools": "安亭小学", "middle_schools": "安亭中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 200, "price_high": 380, "notes": "❌纪要排除"},
    {"district": "嘉定", "plate": "丰庄", "street": "真新街道部分", "primary_schools": "丰庄中学附小", "middle_schools": "丰庄中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 250, "price_high": 420, "notes": "❌纪要排除"},

    # ── 松江（纪要明确排除，含九亭）──
    {"district": "松江", "plate": "九亭", "street": "九亭镇", "primary_schools": "九亭中心小", "middle_schools": "九亭中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 5, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "❌纪要点名排除；早期高竞争段位"},
    {"district": "松江", "plate": "泗泾", "street": "泗泾镇", "primary_schools": "泗泾小学", "middle_schools": "泗泾实验", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 4, "primary_quality": 2, "middle_quality": 2, "price_low": 280, "price_high": 480, "notes": "❌纪要排除"},
    {"district": "松江", "plate": "松江新城", "street": "方松街道", "primary_schools": "松江实验/东华附校", "middle_schools": "松江实验/云间中学", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 300, "price_high": 550, "notes": "❌纪要排除"},
    {"district": "松江", "plate": "松江大学城", "street": "广富林街道", "primary_schools": "东华附校等", "middle_schools": "云间中学等", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 3, "middle_quality": 3, "price_low": 280, "price_high": 500, "notes": "❌纪要排除"},
    {"district": "松江", "plate": "佘山", "street": "佘山镇", "primary_schools": "佘山外国语实验", "middle_schools": "佘山外国语实验", "enrollment": "户籍对口", "five_year": "部分学校", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 350, "price_high": 700, "notes": "❌纪要排除；别墅区"},

    # ── 青浦 ──
    {"district": "青浦", "plate": "徐泾", "street": "徐泾镇", "primary_schools": "徐泾小学", "middle_schools": "徐泾中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 2, "new_resident_ratio": 5, "school_competition": 3, "primary_quality": 2, "middle_quality": 2, "price_low": 350, "price_high": 650, "notes": "大虹桥导入，竞争中等"},
    {"district": "青浦", "plate": "青浦新城", "street": "夏阳/盈浦", "primary_schools": "青浦各公办小", "middle_schools": "青浦各公办初", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 220, "price_high": 400, "notes": "远郊新城"},
    {"district": "青浦", "plate": "朱家角", "street": "朱家角镇", "primary_schools": "朱家角小学", "middle_schools": "朱家角中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 1, "primary_quality": 1, "middle_quality": 1, "price_low": 180, "price_high": 350, "notes": "人口少，竞争极低但学校一般"},

    # ── 奉贤 ──
    {"district": "奉贤", "plate": "南桥", "street": "南桥镇", "primary_schools": "南桥小学", "middle_schools": "奉贤中学附初", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 3, "new_resident_ratio": 4, "school_competition": 2, "primary_quality": 2, "middle_quality": 2, "price_low": 200, "price_high": 380, "notes": "远郊新城"},
    {"district": "奉贤", "plate": "奉城", "street": "奉城镇", "primary_schools": "奉城第一小学", "middle_schools": "奉城中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 1, "primary_quality": 1, "middle_quality": 1, "price_low": 120, "price_high": 250, "notes": "远郊，竞争极低"},

    # ── 金山 ──
    {"district": "金山", "plate": "金山新城", "street": "山阳镇", "primary_schools": "金山各公办小", "middle_schools": "金山各公办初", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 3, "school_competition": 1, "primary_quality": 1, "middle_quality": 1, "price_low": 120, "price_high": 250, "notes": "远郊，学校容量>人口"},
    {"district": "金山", "plate": "石化", "street": "石化街道", "primary_schools": "石化第一小学", "middle_schools": "石化中学", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 4, "new_resident_ratio": 2, "school_competition": 1, "primary_quality": 1, "middle_quality": 1, "price_low": 100, "price_high": 200, "notes": "老工业镇，人口老龄化"},

    # ── 崇明 ──
    {"district": "崇明", "plate": "城桥", "street": "城桥镇", "primary_schools": "崇明各公办小", "middle_schools": "崇明各公办初", "enrollment": "户籍对口", "five_year": "部分", "population_hollow": 5, "new_resident_ratio": 2, "school_competition": 1, "primary_quality": 1, "middle_quality": 1, "price_low": 80, "price_high": 180, "notes": "人口空心化极端，但学校资源有限"},
]

# 中心城区（七区 + 浦东）
CENTRAL_DISTRICTS = {"黄浦", "杨浦", "静安", "徐汇", "长宁", "普陀", "虹口", "浦东"}

# 纪要明确排除的区（整区标记）
EXCLUDED_DISTRICTS = {"嘉定", "松江"}

# 纪要明确排除的区（大部分板块，仅保留例外）
MOSTLY_EXCLUDED_DISTRICTS = {"闵行", "浦东", "宝山"}

# 纪要明确推荐的板块（强制提升等级）
EXPLICIT_RECOMMEND = {
    ("黄浦", "半淞园路"), ("黄浦", "打浦桥"), ("黄浦", "老西门"), ("黄浦", "豫园"),
    ("黄浦", "外滩"), ("黄浦", "南京东路"), ("黄浦", "小东门"),
    ("杨浦", "东外滩/杨浦滨江"),
    ("浦东", "潍坊新村"),
}

# 纪要明确点名排除的板块
EXPLICIT_EXCLUDE = {
    ("松江", "九亭"),
}
